function Comp = addComponents2Panel_View(hPanel)

FC = [255 255 102]/255;

% axes
Comp.hAxis.Image = axes('Parent',                   hPanel, ...
                            'color',        'none',...
                            'xcolor', FC,...
                            'ycolor', FC, ...
                            'gridcolor',   FC,...
                            'Units',                    'normalized', ...
                            'HandleVisibility',     'callback', ...
                            'Position',                 [0.05 0.025 0.9 0.9]);

% Comp.hAxis.Image.XAxisLocation='top';
hold(Comp.hAxis.Image, 'on')

Comp.hPlotObj.Image = imshow([], 'parent', Comp.hAxis.Image);
% axis tight
