 function Comp = addComponents2Panel_Menu(hPanel)

h_Gap = 0.025; 

nB = 10;
h_Button = (1-h_Gap*(nB+1))/nB;

 w_Button = 0.8;
 x_Button = (1-w_Button)/2;

BC_PB = [1 1 1]*0.25;

% load image
h = 1;
h = h-h_Gap-h_Button;
Comp.Togglebutton.Start = uicontrol('parent', hPanel, ...
                                'Style', 'togglebutton',...
                                'String', 'Start',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', 14, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'g',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Togglebutton_Start);
                           